services:
  app:
    build: ./php
    volumes:
      - ./src:/var/www/src
      - ./php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_app
      DB_USERNAME: root
      DB_PASSWORD: secret
  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel_app
      - LANG=C.UTF-8
volumes:
  db:
